services:
  database:
    image: postgres:latest
    container_name: gym-ops-database
    environment:
      - POSTGRES_DB=gym-ops
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Manila
    ports:
      - 5432:5432
    expose:
      - 5432:5432
    networks:
      - default
    volumes:
      - pg-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  pg-data: