// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: memberships.sql

package database

import (
	"context"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (
    membership_name, membership_length, created_by
) VALUES (
    $1, $2, $3
)
RETURNING id, membership_name, membership_length, created_by, version
`

type CreateMembershipParams struct {
	MembershipName   string `json:"membership_name"`
	MembershipLength int32  `json:"membership_length"`
	CreatedBy        int64  `json:"created_by"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.MembershipName, arg.MembershipLength, arg.CreatedBy)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.MembershipName,
		&i.MembershipLength,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships
WHERE id = $1
`

func (q *Queries) DeleteMembership(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMembership, id)
	return err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT id, membership_name, membership_length, created_by, version FROM memberships
WHERE id = $1
`

func (q *Queries) GetMembershipByID(ctx context.Context, id int64) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.MembershipName,
		&i.MembershipLength,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const getMembershipsByUserID = `-- name: GetMembershipsByUserID :many
SELECT id, membership_name, membership_length, created_by, version FROM memberships
WHERE created_by = $1
`

func (q *Queries) GetMembershipsByUserID(ctx context.Context, createdBy int64) ([]Membership, error) {
	rows, err := q.db.Query(ctx, getMembershipsByUserID, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.MembershipName,
			&i.MembershipLength,
			&i.CreatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembership = `-- name: UpdateMembership :one
UPDATE memberships
    set membership_name = $2,
    membership_length = $3,
    version = version + 1
WHERE id = $1 AND version = $4
RETURNING version
`

type UpdateMembershipParams struct {
	ID               int64  `json:"id"`
	MembershipName   string `json:"membership_name"`
	MembershipLength int32  `json:"membership_length"`
	Version          int32  `json:"version"`
}

func (q *Queries) UpdateMembership(ctx context.Context, arg UpdateMembershipParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateMembership,
		arg.ID,
		arg.MembershipName,
		arg.MembershipLength,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
