name: Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'feat/**'

permissions:
  contents: read

jobs:
  build:
    name: Audit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: ESLint Check
        run: pnpm run lint
      - name: Prettier Check
        run: pnpm run prettier:check
